
const API=localStorage.getItem('HC_API')||'https://healthcare-backend-lufm.onrender.com';
let token=localStorage.getItem('HC_ADMIN_TOKEN')||'';
const nav=['Dashboard','Users','Medical Help','Healthcare Network','Offers & Camps','Payments','Notifications'];
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{}),...(token?{Authorization:'Bearer '+token}:{})}});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}if(!r.ok)throw new Error(data?.error||'Request failed');return data}
function login(){document.querySelector('#app').innerHTML=`<div class="login"><div class="card"><h2>Healthcare Admin</h2><p class="muted">Login with mobile OTP.</p><input id="mobile" class="input" placeholder="Mobile number" style="width:100%;margin:7px 0"><button class="btn primary" onclick="requestOtp()" style="width:100%">Send OTP</button><div id="msg"></div></div></div>`}
async function requestOtp(){try{const mobile=document.querySelector('#mobile').value.trim();const d=await api('/api/v1/auth/request-otp',{method:'POST',body:JSON.stringify({mobile})});document.querySelector('#msg').innerHTML=`<p class="muted">OTP sent. Development OTP: <b>${d.dev_otp||'check SMS provider'}</b></p><input id="otp" class="input" placeholder="OTP" style="width:100%"><button class="btn primary" onclick="verifyOtp()" style="margin-top:8px;width:100%">Verify</button>`}catch(e){document.querySelector('#msg').innerHTML=`<p class="error">${e.message}</p>`}}
async function verifyOtp(){try{const mobile=document.querySelector('#mobile').value.trim(),otp=document.querySelector('#otp').value.trim();const d=await api('/api/v1/auth/verify-otp',{method:'POST',body:JSON.stringify({mobile,otp})});token=d.token;localStorage.setItem('HC_ADMIN_TOKEN',token);await api('/api/v1/admin/users');render('Dashboard')}catch(e){document.querySelector('#msg').innerHTML=`<p class="error">${e.message}. This account must have ADMIN role.</p>`}}
function logout(){localStorage.removeItem('HC_ADMIN_TOKEN');token='';login()}
async function render(page='Dashboard'){document.querySelector('#app').innerHTML=`<aside class="side"><div class="brand">Healthcare Admin</div><div class="nav">${nav.map(x=>`<button class="${x===page?'active':''}" onclick="render('${x}')">${x}</button>`).join('')}<button onclick="logout()">Logout</button></div></aside><main class="main"><div class="top"><div><h1>${page}</h1><div class="muted">Connected to ${API}</div></div><button class="btn" onclick="localStorage.setItem('HC_API',prompt('API URL',API)||API);location.reload()">API Settings</button></div><div id="content"></div></main>`;try{document.querySelector('#content').innerHTML=await content(page)}catch(e){document.querySelector('#content').innerHTML=`<div class="error">${e.message}</div>`}}
async function content(p){if(p==='Dashboard'){const d=await api('/api/v1/admin/stats');return `<div class="grid">${metric('Total Users',d.users)}${metric('Pro Users',d.pro_users)}${metric('Medical Help',d.medical_help)}${metric('Partners',d.partners)}</div><div class="grid section">${metric('Pending Partners',d.pending_partners)}${metric('Published Updates',d.published_updates)}${metric('API','OK')}${metric('Role','ADMIN')}</div>`}
if(p==='Users'){const d=await api('/api/v1/admin/users');return table(['Name','Mobile','Plan','Role','Status'],d.map(x=>[x.name||'—',x.mobile,x.plan,x.role,x.status]))}
if(p==='Medical Help'){const d=await api('/api/v1/admin/medical-help');return table(['Request','User','Status','Created'],d.map(x=>[x.details,x.user_id,x.status,new Date(x.created_at).toLocaleString()]))}
if(p==='Healthcare Network'){const d=await api('/api/v1/admin/partners');return table(['Name','Type','City','Status'],d.map(x=>[x.name,x.type,x.city||'—',x.status]))}
if(p==='Offers & Camps'){return `<div class="card"><h2>Offers & Camps</h2><p class="muted">Create a draft update and publish it after review.</p><div class="toolbar"><input id="ot" class="input" placeholder="Title"><input id="od" class="input" placeholder="Description"><input id="ol" class="input" placeholder="Location"><button class="btn primary" onclick="createOffer()">Create Draft</button></div></div>`}
if(p==='Payments'){return `<div class="card"><h2>Payments</h2><p class="muted">Razorpay order/webhook processing is in the Go backend. A dedicated admin payment-list endpoint is the next API addition.</p></div>`}
return `<div class="card"><h2>${p}</h2><p class="muted">Notification management UI will use the existing FCM/device-token backend.</p></div>`}
function metric(a,b){return `<div class="card"><div class="muted">${a}</div><div class="metric">${b}</div></div>`}
function table(headers,rows){return `<div class="card"><div style="overflow:auto"><table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">No data</td></tr>`}</tbody></table></div></div>`}
if(token){api('/api/v1/admin/users').then(()=>render()).catch(()=>login())}else login()

async function createOffer(){try{await api('/api/v1/admin/offers',{method:'POST',body:JSON.stringify({title:document.querySelector('#ot').value,description:document.querySelector('#od').value,location:document.querySelector('#ol').value})});alert('Draft created');render('Offers & Camps')}catch(e){alert(e.message)}}
